environment: dev
log_level: "debug"
server:
  port: 8080
database:
  dsn: "postgres://username:password@host-name/db-name?sslmode=disable"
  redis: "redis-db:6379"

smtp:
  listen_address: "127.0.0.1:2525"
  domain: "mx.some-domain.com" # the hostname this server advertises to connecting MTAs during the SMTP handshake
  email_size_max_mb: 25
  max_line_length: 2048
  email_domain: "gmail.com"
  read_timeout_seconds: 10
  write_timeout_seconds: 10
  api_url: "http://localhost:8080" # The base URL of the core API
  mta_auth_token: "development-edge-token-123" # The authentication token for the MTA to use when sending data to the core API

storage:
  aws_region: "us-east-1" # AWS region where the S3 bucket is located
  s3_base_endpoint: "objstore.some-domain.com" # Base endpoint for S3-compatible storage (e.g., MinIO), set empty for AWS S3.
  use_path_style: true # Use path-style addressing for S3 (true for MinIO, false for AWS S3), not used if s3_base_endpoint is empty.
  s3_bucket: "email-ingestion-storage-dev" # S3 bucket for storing processed emails.
  ingestion_prefix: "tmp/" # S3 prefix for storing raw email files before they are processed
  storage_prefix: "storage/" # S3 prefix for storing processed email files after, converting the raw EML to a json file exclding the attachments.

webhook:
  allowed_domains:
    - "localhost"
    - "internal.some-domain.com"

auth:
  provider: "password" # options: "password" | "oidc"
  admin: # Admin user credentials for local password auth. Not used if auth.provider is set to "oidc".
    username: "admin"
    password: "admin123-change-me"
    jwt_secret: "dev-dashboard-jwt-secret-key-change-in-prod" # Or env EM_AUTH_JWT_SECRET, only when provider is "password"
    authority: "dev-application" # Issuer for JWT tokens. Only used when provider is "password
    token_ttl_minutes: 1440
  oidc:
    authority: https://auth.some-domain.com
    client_id: client-id-dev
    jwks_uri: https://auth.some-domain.com/.well-known/jwks
