/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/addresses/': RouteRecordInfo<
      '/addresses/',
      '/addresses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/Callback': RouteRecordInfo<
      '/auth/Callback',
      '/auth/Callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/Logout': RouteRecordInfo<
      '/auth/Logout',
      '/auth/Logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/emails/': RouteRecordInfo<
      '/emails/',
      '/emails',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/emails/[id]': RouteRecordInfo<
      '/emails/[id]',
      '/emails/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'need-invitation': RouteRecordInfo<
      'need-invitation',
      '/need-invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/webhooks/': RouteRecordInfo<
      '/webhooks/',
      '/webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/addresses/index.vue': {
      routes:
        | '/addresses/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/Callback.vue': {
      routes:
        | '/auth/Callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/Logout.vue': {
      routes:
        | '/auth/Logout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/emails/index.vue': {
      routes:
        | '/emails/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/emails/[id].vue': {
      routes:
        | '/emails/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NeedInvitation.vue': {
      routes:
        | 'need-invitation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/webhooks/index.vue': {
      routes:
        | '/webhooks/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
