// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package public

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WebhookStatus string

const (
	WebhookStatusPENDING    WebhookStatus = "PENDING"
	WebhookStatusPROCESSING WebhookStatus = "PROCESSING"
	WebhookStatusSUCCESS    WebhookStatus = "SUCCESS"
	WebhookStatusFAILED     WebhookStatus = "FAILED"
	WebhookStatusDEAD       WebhookStatus = "DEAD"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhookStatus"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type Application struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	ApiKeyHash    string             `json:"apiKeyHash"`
	WebhookUrl    string             `json:"webhookUrl"`
	WebhookSecret string             `json:"webhookSecret"`
	AwsIamRoleArn string             `json:"awsIamRoleArn"`
	MaxRetries    int32              `json:"maxRetries"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type AssignedEmail struct {
	ID            uuid.UUID          `json:"id"`
	ApplicationID uuid.UUID          `json:"applicationId"`
	LocalPart     string             `json:"localPart"`
	Description   pgtype.Text        `json:"description"`
	IsActive      bool               `json:"isActive"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type IngestedEmail struct {
	ID              uuid.UUID          `json:"id"`
	ApplicationID   uuid.UUID          `json:"applicationId"`
	AssignedEmailID uuid.UUID          `json:"assignedEmailId"`
	ReferenceToken  string             `json:"referenceToken"`
	FromAddress     string             `json:"fromAddress"`
	Subject         string             `json:"subject"`
	MessageID       string             `json:"messageId"`
	S3KeyPrefix     string             `json:"s3KeyPrefix"`
	ReceivedAt      pgtype.Timestamptz `json:"receivedAt"`
}

type WebhookDeliveryJob struct {
	ID              uuid.UUID          `json:"id"`
	ApplicationID   uuid.UUID          `json:"applicationId"`
	IngestedEmailID uuid.UUID          `json:"ingestedEmailId"`
	Status          WebhookStatus      `json:"status"`
	RetryCount      int32              `json:"retryCount"`
	NextDeliveryAt  pgtype.Timestamptz `json:"nextDeliveryAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type WebhookLog struct {
	ID                   uuid.UUID          `json:"id"`
	WebhookDeliveryJobID uuid.UUID          `json:"webhookDeliveryJobId"`
	AttemptNumber        int32              `json:"attemptNumber"`
	HttpStatusCode       pgtype.Int4        `json:"httpStatusCode"`
	ResponseBody         pgtype.Text        `json:"responseBody"`
	IsRetry              bool               `json:"isRetry"`
	DurationMs           int32              `json:"durationMs"`
	ExecutedAt           pgtype.Timestamptz `json:"executedAt"`
}
