// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package public

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SpoolStatus string

const (
	SpoolStatusPENDING    SpoolStatus = "PENDING"
	SpoolStatusPROCESSING SpoolStatus = "PROCESSING"
	SpoolStatusSUCCESS    SpoolStatus = "SUCCESS"
	SpoolStatusFAILED     SpoolStatus = "FAILED"
	SpoolStatusDEAD       SpoolStatus = "DEAD"
)

func (e *SpoolStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpoolStatus(s)
	case string:
		*e = SpoolStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SpoolStatus: %T", src)
	}
	return nil
}

type NullSpoolStatus struct {
	SpoolStatus SpoolStatus `json:"spoolStatus"`
	Valid       bool        `json:"valid"` // Valid is true if SpoolStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpoolStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SpoolStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpoolStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpoolStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpoolStatus), nil
}

type WebhookStatus string

const (
	WebhookStatusPENDING    WebhookStatus = "PENDING"
	WebhookStatusPROCESSING WebhookStatus = "PROCESSING"
	WebhookStatusSUCCESS    WebhookStatus = "SUCCESS"
	WebhookStatusFAILED     WebhookStatus = "FAILED"
	WebhookStatusDEAD       WebhookStatus = "DEAD"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhookStatus"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type ApiKey struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
	Name          string    `json:"name"`
	KeyPrefix     string    `json:"keyPrefix"`
	KeyHash       string    `json:"keyHash"`
	CreatedAt     time.Time `json:"createdAt"`
	ExpiresAt     time.Time `json:"expiresAt"`
	LastUsedAt    time.Time `json:"lastUsedAt"`
}

type Application struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	WebhookUrl     string      `json:"webhookUrl"`
	WebhookSecret  string      `json:"webhookSecret"`
	AwsIamRoleArn  string      `json:"awsIamRoleArn"`
	MaxRetries     int32       `json:"maxRetries"`
	IsTrusted      bool        `json:"isTrusted"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
	OrganizationID pgtype.UUID `json:"organizationId"`
}

type AssignedEmail struct {
	ID            uuid.UUID   `json:"id"`
	ApplicationID uuid.UUID   `json:"applicationId"`
	LocalPart     string      `json:"localPart"`
	Description   pgtype.Text `json:"description"`
	IsActive      bool        `json:"isActive"`
	CreatedAt     time.Time   `json:"createdAt"`
}

type InboundSpoolQueue struct {
	ID               uuid.UUID   `json:"id"`
	S3ObjectKey      string      `json:"s3ObjectKey"`
	Status           SpoolStatus `json:"status"`
	AttemptCount     int32       `json:"attemptCount"`
	LastErrorMessage string      `json:"lastErrorMessage"`
	CreatedAt        time.Time   `json:"createdAt"`
	UpdatedAt        time.Time   `json:"updatedAt"`
}

type IngestedEmail struct {
	ID              uuid.UUID `json:"id"`
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
	ReceivedAt      time.Time `json:"receivedAt"`
}

type Organization struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"ownerUserId"`
	IsPersonal  bool      `json:"isPersonal"`
	CreatedAt   time.Time `json:"createdAt"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	IdpUserSub  string    `json:"idpUserSub"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	ActivatedAt time.Time `json:"activatedAt"`
	LastLoginAt time.Time `json:"lastLoginAt"`
}

type UserApplicationAccess struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
	UserID        uuid.UUID `json:"userId"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type WebhookDeliveryJob struct {
	ID              uuid.UUID     `json:"id"`
	ApplicationID   uuid.UUID     `json:"applicationId"`
	IngestedEmailID uuid.UUID     `json:"ingestedEmailId"`
	Status          WebhookStatus `json:"status"`
	RetryCount      int32         `json:"retryCount"`
	NextDeliveryAt  time.Time     `json:"nextDeliveryAt"`
	CreatedAt       time.Time     `json:"createdAt"`
}

type WebhookLog struct {
	ID                   uuid.UUID `json:"id"`
	WebhookDeliveryJobID uuid.UUID `json:"webhookDeliveryJobId"`
	AttemptNumber        int32     `json:"attemptNumber"`
	HttpStatusCode       int32     `json:"httpStatusCode"`
	ResponseBody         string    `json:"responseBody"`
	IsRetry              bool      `json:"isRetry"`
	DurationMs           int32     `json:"durationMs"`
	ExecutedAt           time.Time `json:"executedAt"`
}
