// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.public.sql

package public

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignedEmail = `-- name: CreateAssignedEmail :one
INSERT INTO assigned_emails (application_id, local_part, description)  
VALUES ($1, $2, $3)  
RETURNING id, application_id, local_part, description, is_active, created_at
`

type CreateAssignedEmailParams struct {
	ApplicationID uuid.UUID   `json:"applicationId"`
	LocalPart     string      `json:"localPart"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateAssignedEmail(ctx context.Context, arg CreateAssignedEmailParams) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, createAssignedEmail, arg.ApplicationID, arg.LocalPart, arg.Description)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createIngestedEmail = `-- name: CreateIngestedEmail :one
INSERT INTO ingested_emails (application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix)  
VALUES ($1, $2, $3, $4, $5, $6, $7)  
RETURNING id, application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix, received_at
`

type CreateIngestedEmailParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
}

func (q *Queries) CreateIngestedEmail(ctx context.Context, arg CreateIngestedEmailParams) (IngestedEmail, error) {
	row := q.db.QueryRow(ctx, createIngestedEmail,
		arg.ApplicationID,
		arg.AssignedEmailID,
		arg.ReferenceToken,
		arg.FromAddress,
		arg.Subject,
		arg.MessageID,
		arg.S3KeyPrefix,
	)
	var i IngestedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.AssignedEmailID,
		&i.ReferenceToken,
		&i.FromAddress,
		&i.Subject,
		&i.MessageID,
		&i.S3KeyPrefix,
		&i.ReceivedAt,
	)
	return i, err
}

const enqueueWebhookJob = `-- name: EnqueueWebhookJob :one
INSERT INTO webhook_delivery_jobs (application_id, ingested_email_id, next_delivery_at)  
VALUES ($1, $2, CURRENT_TIMESTAMP)  
RETURNING id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at
`

type EnqueueWebhookJobParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) EnqueueWebhookJob(ctx context.Context, arg EnqueueWebhookJobParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookJob, arg.ApplicationID, arg.IngestedEmailID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationByAPIKey = `-- name: GetApplicationByAPIKey :one
SELECT id, name, api_key_hash, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, created_at, updated_at FROM applications WHERE api_key_hash = $1 LIMIT 1
`

func (q *Queries) GetApplicationByAPIKey(ctx context.Context, apiKeyHash string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByAPIKey, apiKeyHash)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationWithEmails = `-- name: GetApplicationWithEmails :many
SELECT a.id, a.name, a.api_key_hash, a.webhook_url, a.webhook_secret, a.aws_iam_role_arn, a.max_retries, a.created_at, a.updated_at, e.id AS email_id, e.local_part, e.description, e.is_active, e.created_at AS email_created_at  
FROM applications a  
LEFT JOIN assigned_emails e ON a.id = e.application_id  
WHERE a.id = $1
`

type GetApplicationWithEmailsRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	ApiKeyHash     string             `json:"apiKeyHash"`
	WebhookUrl     string             `json:"webhookUrl"`
	WebhookSecret  string             `json:"webhookSecret"`
	AwsIamRoleArn  string             `json:"awsIamRoleArn"`
	MaxRetries     int32              `json:"maxRetries"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	EmailID        pgtype.UUID        `json:"emailId"`
	LocalPart      pgtype.Text        `json:"localPart"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"isActive"`
	EmailCreatedAt pgtype.Timestamptz `json:"emailCreatedAt"`
}

func (q *Queries) GetApplicationWithEmails(ctx context.Context, id uuid.UUID) ([]GetApplicationWithEmailsRow, error) {
	rows, err := q.db.Query(ctx, getApplicationWithEmails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationWithEmailsRow
	for rows.Next() {
		var i GetApplicationWithEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.AwsIamRoleArn,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailID,
			&i.LocalPart,
			&i.Description,
			&i.IsActive,
			&i.EmailCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedEmailByLocalPart = `-- name: GetAssignedEmailByLocalPart :one
SELECT id, application_id, local_part, description, is_active, created_at FROM assigned_emails WHERE local_part = $1 AND is_active = TRUE LIMIT 1
`

func (q *Queries) GetAssignedEmailByLocalPart(ctx context.Context, localPart string) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, getAssignedEmailByLocalPart, localPart)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingWebhookJobs = `-- name: GetPendingWebhookJobs :many
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs  
WHERE status = 'PENDING' AND next_delivery_at <= CURRENT_TIMESTAMP  
LIMIT $1
`

func (q *Queries) GetPendingWebhookJobs(ctx context.Context, limit int32) ([]WebhookDeliveryJob, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDeliveryJob
	for rows.Next() {
		var i WebhookDeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.IngestedEmailID,
			&i.Status,
			&i.RetryCount,
			&i.NextDeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWebhookAttempt = `-- name: LogWebhookAttempt :exec
INSERT INTO webhook_logs (webhook_delivery_job_id, attempt_number, http_status_code, response_body, is_retry, duration_ms)  
VALUES ($1, $2, $3, $4, $5, $6)
`

type LogWebhookAttemptParams struct {
	WebhookDeliveryJobID uuid.UUID   `json:"webhookDeliveryJobId"`
	AttemptNumber        int32       `json:"attemptNumber"`
	HttpStatusCode       pgtype.Int4 `json:"httpStatusCode"`
	ResponseBody         pgtype.Text `json:"responseBody"`
	IsRetry              bool        `json:"isRetry"`
	DurationMs           int32       `json:"durationMs"`
}

func (q *Queries) LogWebhookAttempt(ctx context.Context, arg LogWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, logWebhookAttempt,
		arg.WebhookDeliveryJobID,
		arg.AttemptNumber,
		arg.HttpStatusCode,
		arg.ResponseBody,
		arg.IsRetry,
		arg.DurationMs,
	)
	return err
}

const updateWebhookJobStatus = `-- name: UpdateWebhookJobStatus :exec
UPDATE webhook_delivery_jobs  
SET status = $2, retry_count = $3, next_delivery_at = $4  
WHERE id = $1
`

type UpdateWebhookJobStatusParams struct {
	ID             uuid.UUID          `json:"id"`
	Status         WebhookStatus      `json:"status"`
	RetryCount     int32              `json:"retryCount"`
	NextDeliveryAt pgtype.Timestamptz `json:"nextDeliveryAt"`
}

func (q *Queries) UpdateWebhookJobStatus(ctx context.Context, arg UpdateWebhookJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookJobStatus,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.NextDeliveryAt,
	)
	return err
}
