// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.public.sql

package public

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWebhookJob = `-- name: CancelWebhookJob :exec
UPDATE webhook_delivery_jobs
SET status = 'DEAD'
WHERE id = $1 AND application_id = $2 AND status IN ('PENDING', 'FAILED')
`

type CancelWebhookJobParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) CancelWebhookJob(ctx context.Context, arg CancelWebhookJobParams) error {
	_, err := q.db.Exec(ctx, cancelWebhookJob, arg.ID, arg.ApplicationID)
	return err
}

const checkDuplicateWebhookJob = `-- name: CheckDuplicateWebhookJob :one
SELECT EXISTS (
  SELECT 1 FROM webhook_delivery_jobs  
  WHERE application_id = $1 AND ingested_email_id = $2
)
`

type CheckDuplicateWebhookJobParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) CheckDuplicateWebhookJob(ctx context.Context, arg CheckDuplicateWebhookJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDuplicateWebhookJob, arg.ApplicationID, arg.IngestedEmailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countIngestedEmailsByApplication = `-- name: CountIngestedEmailsByApplication :one
SELECT count(*) FROM ingested_emails WHERE application_id = $1
`

func (q *Queries) CountIngestedEmailsByApplication(ctx context.Context, applicationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestedEmailsByApplication, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :exec
INSERT INTO api_keys (application_id, name, key_prefix, key_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateApiKeyParams struct {
	ApplicationID uuid.UUID `json:"applicationId"`
	Name          string    `json:"name"`
	KeyPrefix     string    `json:"keyPrefix"`
	KeyHash       string    `json:"keyHash"`
	CreatedAt     time.Time `json:"createdAt"`
	ExpiresAt     time.Time `json:"expiresAt"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) error {
	_, err := q.db.Exec(ctx, createApiKey,
		arg.ApplicationID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createAssignedEmail = `-- name: CreateAssignedEmail :one
INSERT INTO assigned_emails (application_id, local_part, description)  
VALUES ($1, $2, $3)  
RETURNING id, application_id, local_part, description, is_active, created_at
`

type CreateAssignedEmailParams struct {
	ApplicationID uuid.UUID   `json:"applicationId"`
	LocalPart     string      `json:"localPart"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateAssignedEmail(ctx context.Context, arg CreateAssignedEmailParams) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, createAssignedEmail, arg.ApplicationID, arg.LocalPart, arg.Description)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createInboundSpooledEmail = `-- name: CreateInboundSpooledEmail :one
INSERT INTO inbound_spool_queue (id, s3_object_key, status, attempt_count, last_error_message, created_at, updated_at)  
VALUES ($1, $2, $3, $4, $5, $6, $7)  
RETURNING id, s3_object_key, status, attempt_count, last_error_message, created_at, updated_at
`

type CreateInboundSpooledEmailParams struct {
	ID               uuid.UUID   `json:"id"`
	S3ObjectKey      string      `json:"s3ObjectKey"`
	Status           SpoolStatus `json:"status"`
	AttemptCount     int32       `json:"attemptCount"`
	LastErrorMessage string      `json:"lastErrorMessage"`
	CreatedAt        time.Time   `json:"createdAt"`
	UpdatedAt        time.Time   `json:"updatedAt"`
}

func (q *Queries) CreateInboundSpooledEmail(ctx context.Context, arg CreateInboundSpooledEmailParams) (InboundSpoolQueue, error) {
	row := q.db.QueryRow(ctx, createInboundSpooledEmail,
		arg.ID,
		arg.S3ObjectKey,
		arg.Status,
		arg.AttemptCount,
		arg.LastErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InboundSpoolQueue
	err := row.Scan(
		&i.ID,
		&i.S3ObjectKey,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIngestedEmail = `-- name: CreateIngestedEmail :one
INSERT INTO ingested_emails (application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix)  
VALUES ($1, $2, $3, $4, $5, $6, $7)  
RETURNING id, application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix, received_at
`

type CreateIngestedEmailParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
}

func (q *Queries) CreateIngestedEmail(ctx context.Context, arg CreateIngestedEmailParams) (IngestedEmail, error) {
	row := q.db.QueryRow(ctx, createIngestedEmail,
		arg.ApplicationID,
		arg.AssignedEmailID,
		arg.ReferenceToken,
		arg.FromAddress,
		arg.Subject,
		arg.MessageID,
		arg.S3KeyPrefix,
	)
	var i IngestedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.AssignedEmailID,
		&i.ReferenceToken,
		&i.FromAddress,
		&i.Subject,
		&i.MessageID,
		&i.S3KeyPrefix,
		&i.ReceivedAt,
	)
	return i, err
}

const createPersonalOrganization = `-- name: CreatePersonalOrganization :one
INSERT INTO organizations (name, owner_user_id, is_personal)
VALUES ($1, $2, true)
ON CONFLICT (owner_user_id) WHERE is_personal = true
DO UPDATE SET name = organizations.name
RETURNING id, name, owner_user_id, is_personal, created_at
`

type CreatePersonalOrganizationParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"ownerUserId"`
}

func (q *Queries) CreatePersonalOrganization(ctx context.Context, arg CreatePersonalOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createPersonalOrganization, arg.Name, arg.OwnerUserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys
WHERE id = $1 AND application_id = $2
`

type DeleteApiKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.ApplicationID)
	return err
}

const enqueueWebhookJob = `-- name: EnqueueWebhookJob :one
INSERT INTO webhook_delivery_jobs (application_id, ingested_email_id, next_delivery_at)  
VALUES ($1, $2, CURRENT_TIMESTAMP)  
RETURNING id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at
`

type EnqueueWebhookJobParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) EnqueueWebhookJob(ctx context.Context, arg EnqueueWebhookJobParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookJob, arg.ApplicationID, arg.IngestedEmailID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminApplications = `-- name: GetAdminApplications :many
SELECT id, name, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, created_at, updated_at, organization_id FROM applications
`

func (q *Queries) GetAdminApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, getAdminApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.AwsIamRoleArn,
			&i.MaxRetries,
			&i.IsTrusted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApiKeyByKeyHash = `-- name: GetApiKeyByKeyHash :one
SELECT id, application_id, name, key_prefix, key_hash, created_at, expires_at, last_used_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetApiKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByKeyHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getApplicationByAPIKey = `-- name: GetApplicationByAPIKey :one
SELECT a.id, a.name, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, a.created_at, updated_at, organization_id, ak.id, application_id, ak.name, key_prefix, key_hash, ak.created_at, expires_at, last_used_at FROM applications a
JOIN api_keys ak ON ak.application_id = a.id
WHERE key_hash = $1 LIMIT 1
`

type GetApplicationByAPIKeyRow struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	WebhookUrl     string      `json:"webhookUrl"`
	WebhookSecret  string      `json:"webhookSecret"`
	AwsIamRoleArn  string      `json:"awsIamRoleArn"`
	MaxRetries     int32       `json:"maxRetries"`
	IsTrusted      bool        `json:"isTrusted"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
	OrganizationID pgtype.UUID `json:"organizationId"`
	ID_2           uuid.UUID   `json:"id2"`
	ApplicationID  uuid.UUID   `json:"applicationId"`
	Name_2         string      `json:"name2"`
	KeyPrefix      string      `json:"keyPrefix"`
	KeyHash        string      `json:"keyHash"`
	CreatedAt_2    time.Time   `json:"createdAt2"`
	ExpiresAt      time.Time   `json:"expiresAt"`
	LastUsedAt     time.Time   `json:"lastUsedAt"`
}

func (q *Queries) GetApplicationByAPIKey(ctx context.Context, keyHash string) (GetApplicationByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByAPIKey, keyHash)
	var i GetApplicationByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.IsTrusted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.ID_2,
		&i.ApplicationID,
		&i.Name_2,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt_2,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, created_at, updated_at, organization_id FROM applications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.IsTrusted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getApplicationWithEmails = `-- name: GetApplicationWithEmails :many
SELECT a.id, a.name, a.webhook_url, a.webhook_secret, a.aws_iam_role_arn, a.max_retries, a.is_trusted, a.created_at, a.updated_at, a.organization_id, e.id AS email_id, e.local_part, e.description, e.is_active, e.created_at AS email_created_at  
FROM applications a  
LEFT JOIN assigned_emails e ON a.id = e.application_id  
WHERE a.id = $1
`

type GetApplicationWithEmailsRow struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	WebhookUrl     string      `json:"webhookUrl"`
	WebhookSecret  string      `json:"webhookSecret"`
	AwsIamRoleArn  string      `json:"awsIamRoleArn"`
	MaxRetries     int32       `json:"maxRetries"`
	IsTrusted      bool        `json:"isTrusted"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
	OrganizationID pgtype.UUID `json:"organizationId"`
	EmailID        pgtype.UUID `json:"emailId"`
	LocalPart      pgtype.Text `json:"localPart"`
	Description    pgtype.Text `json:"description"`
	IsActive       pgtype.Bool `json:"isActive"`
	EmailCreatedAt *time.Time  `json:"emailCreatedAt"`
}

func (q *Queries) GetApplicationWithEmails(ctx context.Context, id uuid.UUID) ([]GetApplicationWithEmailsRow, error) {
	rows, err := q.db.Query(ctx, getApplicationWithEmails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationWithEmailsRow
	for rows.Next() {
		var i GetApplicationWithEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.AwsIamRoleArn,
			&i.MaxRetries,
			&i.IsTrusted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.EmailID,
			&i.LocalPart,
			&i.Description,
			&i.IsActive,
			&i.EmailCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplications = `-- name: GetApplications :many
SELECT a.id, a.name, a.webhook_url, a.webhook_secret, a.aws_iam_role_arn, a.max_retries, a.is_trusted, a.created_at, a.updated_at, a.organization_id FROM applications a
JOIN user_application_access ua ON ua.application_id = a.id
WHERE ua.user_id = $1
`

func (q *Queries) GetApplications(ctx context.Context, userID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, getApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.AwsIamRoleArn,
			&i.MaxRetries,
			&i.IsTrusted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedEmailByLocalPart = `-- name: GetAssignedEmailByLocalPart :one
SELECT id, application_id, local_part, description, is_active, created_at FROM assigned_emails WHERE local_part = $1 AND is_active = TRUE LIMIT 1
`

func (q *Queries) GetAssignedEmailByLocalPart(ctx context.Context, localPart string) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, getAssignedEmailByLocalPart, localPart)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getIngestedEmailByID = `-- name: GetIngestedEmailByID :one
SELECT i.id, i.application_id, i.assigned_email_id, i.reference_token, i.from_address, i.subject, i.message_id, i.s3_key_prefix, i.received_at, a.local_part
FROM ingested_emails i
JOIN assigned_emails a ON a.id = i.assigned_email_id
WHERE i.id = $1 and i.application_id = $2 LIMIT 1
`

type GetIngestedEmailByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

type GetIngestedEmailByIDRow struct {
	ID              uuid.UUID `json:"id"`
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
	ReceivedAt      time.Time `json:"receivedAt"`
	LocalPart       string    `json:"localPart"`
}

func (q *Queries) GetIngestedEmailByID(ctx context.Context, arg GetIngestedEmailByIDParams) (GetIngestedEmailByIDRow, error) {
	row := q.db.QueryRow(ctx, getIngestedEmailByID, arg.ID, arg.ApplicationID)
	var i GetIngestedEmailByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.AssignedEmailID,
		&i.ReferenceToken,
		&i.FromAddress,
		&i.Subject,
		&i.MessageID,
		&i.S3KeyPrefix,
		&i.ReceivedAt,
		&i.LocalPart,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, owner_user_id, is_personal, created_at FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingWebhookJobs = `-- name: GetPendingWebhookJobs :many
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs  
WHERE status = 'PENDING' AND next_delivery_at <= CURRENT_TIMESTAMP  
LIMIT $1
`

func (q *Queries) GetPendingWebhookJobs(ctx context.Context, limit int32) ([]WebhookDeliveryJob, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDeliveryJob
	for rows.Next() {
		var i WebhookDeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.IngestedEmailID,
			&i.Status,
			&i.RetryCount,
			&i.NextDeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalOrganizationByUserID = `-- name: GetPersonalOrganizationByUserID :one
SELECT id, name, owner_user_id, is_personal, created_at FROM organizations
WHERE owner_user_id = $1 AND is_personal = true
LIMIT 1
`

func (q *Queries) GetPersonalOrganizationByUserID(ctx context.Context, ownerUserID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getPersonalOrganizationByUserID, ownerUserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, idp_user_sub, status, created_at, activated_at, last_login_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdpUserSub,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, email, idp_user_sub, status, created_at, activated_at, last_login_at FROM users WHERE idp_user_sub = $1
`

func (q *Queries) GetUserBySubject(ctx context.Context, idpUserSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, idpUserSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdpUserSub,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getWebhookDeliveryStatsByApplication = `-- name: GetWebhookDeliveryStatsByApplication :one
    SELECT
        COUNT(*)::bigint AS total,
        COUNT(*) FILTER (WHERE status = 'SUCCESS')::bigint AS success,
        COUNT(*) FILTER (WHERE status IN ('FAILED', 'DEAD'))::bigint AS failures,
        COUNT(*) FILTER (WHERE status IN ('PENDING', 'PROCESSING'))::bigint AS pending_or_processing
    FROM public.webhook_delivery_jobs
    WHERE application_id = $1
`

type GetWebhookDeliveryStatsByApplicationRow struct {
	Total               int64 `json:"total"`
	Success             int64 `json:"success"`
	Failures            int64 `json:"failures"`
	PendingOrProcessing int64 `json:"pendingOrProcessing"`
}

func (q *Queries) GetWebhookDeliveryStatsByApplication(ctx context.Context, applicationID uuid.UUID) (GetWebhookDeliveryStatsByApplicationRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryStatsByApplication, applicationID)
	var i GetWebhookDeliveryStatsByApplicationRow
	err := row.Scan(
		&i.Total,
		&i.Success,
		&i.Failures,
		&i.PendingOrProcessing,
	)
	return i, err
}

const getWebhookJobByIDAndAppID = `-- name: GetWebhookJobByIDAndAppID :one
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs
WHERE id = $1 AND application_id = $2
LIMIT 1
`

type GetWebhookJobByIDAndAppIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) GetWebhookJobByIDAndAppID(ctx context.Context, arg GetWebhookJobByIDAndAppIDParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, getWebhookJobByIDAndAppID, arg.ID, arg.ApplicationID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookJobByIDs = `-- name: GetWebhookJobByIDs :one
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs WHERE application_id = $1 AND ingested_email_id = $2 ORDER BY created_at DESC LIMIT 1
`

type GetWebhookJobByIDsParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) GetWebhookJobByIDs(ctx context.Context, arg GetWebhookJobByIDsParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, getWebhookJobByIDs, arg.ApplicationID, arg.IngestedEmailID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookLogsByJobID = `-- name: GetWebhookLogsByJobID :many
SELECT id, webhook_delivery_job_id, attempt_number, http_status_code, response_body, is_retry, duration_ms, executed_at, request_payload FROM webhook_logs
WHERE webhook_delivery_job_id = $1
ORDER BY attempt_number DESC
`

func (q *Queries) GetWebhookLogsByJobID(ctx context.Context, webhookDeliveryJobID uuid.UUID) ([]WebhookLog, error) {
	rows, err := q.db.Query(ctx, getWebhookLogsByJobID, webhookDeliveryJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookLog
	for rows.Next() {
		var i WebhookLog
		if err := rows.Scan(
			&i.ID,
			&i.WebhookDeliveryJobID,
			&i.AttemptNumber,
			&i.HttpStatusCode,
			&i.ResponseBody,
			&i.IsRetry,
			&i.DurationMs,
			&i.ExecutedAt,
			&i.RequestPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (name, organization_id, webhook_url, webhook_secret, aws_iam_role_arn)
VALUES ($1, $2, '', '', '')
RETURNING id, name, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, created_at, updated_at, organization_id
`

type InsertApplicationParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organizationId"`
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, insertApplication, arg.Name, arg.OrganizationID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.IsTrusted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const insertUserApplication = `-- name: InsertUserApplication :exec
INSERT INTO user_application_access (user_id, application_id)
VALUES ($1, $2)
`

type InsertUserApplicationParams struct {
	UserID        uuid.UUID `json:"userId"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) InsertUserApplication(ctx context.Context, arg InsertUserApplicationParams) error {
	_, err := q.db.Exec(ctx, insertUserApplication, arg.UserID, arg.ApplicationID)
	return err
}

const listApiKeysByApplication = `-- name: ListApiKeysByApplication :many
SELECT id, application_id, name, key_prefix, created_at, expires_at, last_used_at
FROM api_keys
WHERE application_id = $1
ORDER BY created_at DESC
`

type ListApiKeysByApplicationRow struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
	Name          string    `json:"name"`
	KeyPrefix     string    `json:"keyPrefix"`
	CreatedAt     time.Time `json:"createdAt"`
	ExpiresAt     time.Time `json:"expiresAt"`
	LastUsedAt    time.Time `json:"lastUsedAt"`
}

func (q *Queries) ListApiKeysByApplication(ctx context.Context, applicationID uuid.UUID) ([]ListApiKeysByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByApplicationRow
	for rows.Next() {
		var i ListApiKeysByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedEmailsByApplication = `-- name: ListAssignedEmailsByApplication :many
SELECT id, application_id, local_part, description, is_active, created_at FROM assigned_emails
WHERE application_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAssignedEmailsByApplication(ctx context.Context, applicationID uuid.UUID) ([]AssignedEmail, error) {
	rows, err := q.db.Query(ctx, listAssignedEmailsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignedEmail
	for rows.Next() {
		var i AssignedEmail
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.LocalPart,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestedEmailsByApplication = `-- name: ListIngestedEmailsByApplication :many
SELECT i.id, i.application_id, i.assigned_email_id, i.reference_token, i.from_address, i.subject, i.message_id, i.s3_key_prefix, i.received_at, a.local_part FROM ingested_emails i
JOIN assigned_emails a ON a.id = i.assigned_email_id
WHERE i.application_id = $1 ORDER BY received_at DESC LIMIT $2 OFFSET $3
`

type ListIngestedEmailsByApplicationParams struct {
	ApplicationID uuid.UUID `json:"applicationId"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

type ListIngestedEmailsByApplicationRow struct {
	ID              uuid.UUID `json:"id"`
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
	ReceivedAt      time.Time `json:"receivedAt"`
	LocalPart       string    `json:"localPart"`
}

func (q *Queries) ListIngestedEmailsByApplication(ctx context.Context, arg ListIngestedEmailsByApplicationParams) ([]ListIngestedEmailsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listIngestedEmailsByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngestedEmailsByApplicationRow
	for rows.Next() {
		var i ListIngestedEmailsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.AssignedEmailID,
			&i.ReferenceToken,
			&i.FromAddress,
			&i.Subject,
			&i.MessageID,
			&i.S3KeyPrefix,
			&i.ReceivedAt,
			&i.LocalPart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookJobsByApplication = `-- name: ListWebhookJobsByApplication :many
SELECT wj.id, wj.application_id, wj.ingested_email_id, wj.status, wj.retry_count, wj.next_delivery_at, wj.created_at,
       COALESCE(wl.http_status_code, 0), COALESCE(wl.duration_ms, 0), COALESCE(wl.attempt_number, 0),
       COALESCE(wl.request_payload, ''), COALESCE(wl.response_body, '')
FROM webhook_delivery_jobs wj
LEFT JOIN LATERAL (
  SELECT http_status_code, duration_ms, attempt_number, request_payload, response_body
  FROM webhook_logs
  WHERE webhook_delivery_job_id = wj.id
  ORDER BY attempt_number DESC
  LIMIT 1
) wl ON TRUE
WHERE wj.application_id = $1
  AND ($4::text IS NULL OR $4::text = '' OR wj.status = $4::webhook_status)
ORDER BY wj.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookJobsByApplicationParams struct {
	ApplicationID uuid.UUID   `json:"applicationId"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	Status        pgtype.Text `json:"status"`
}

type ListWebhookJobsByApplicationRow struct {
	ID              uuid.UUID     `json:"id"`
	ApplicationID   uuid.UUID     `json:"applicationId"`
	IngestedEmailID uuid.UUID     `json:"ingestedEmailId"`
	Status          WebhookStatus `json:"status"`
	RetryCount      int32         `json:"retryCount"`
	NextDeliveryAt  time.Time     `json:"nextDeliveryAt"`
	CreatedAt       time.Time     `json:"createdAt"`
	HttpStatusCode  int32         `json:"httpStatusCode"`
	DurationMs      int32         `json:"durationMs"`
	AttemptNumber   int32         `json:"attemptNumber"`
	RequestPayload  string        `json:"requestPayload"`
	ResponseBody    string        `json:"responseBody"`
}

func (q *Queries) ListWebhookJobsByApplication(ctx context.Context, arg ListWebhookJobsByApplicationParams) ([]ListWebhookJobsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listWebhookJobsByApplication,
		arg.ApplicationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookJobsByApplicationRow
	for rows.Next() {
		var i ListWebhookJobsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.IngestedEmailID,
			&i.Status,
			&i.RetryCount,
			&i.NextDeliveryAt,
			&i.CreatedAt,
			&i.HttpStatusCode,
			&i.DurationMs,
			&i.AttemptNumber,
			&i.RequestPayload,
			&i.ResponseBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWebhookAttempt = `-- name: LogWebhookAttempt :exec
INSERT INTO webhook_logs (webhook_delivery_job_id, attempt_number, http_status_code, request_payload, response_body, is_retry, duration_ms)  
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type LogWebhookAttemptParams struct {
	WebhookDeliveryJobID uuid.UUID `json:"webhookDeliveryJobId"`
	AttemptNumber        int32     `json:"attemptNumber"`
	HttpStatusCode       int32     `json:"httpStatusCode"`
	RequestPayload       string    `json:"requestPayload"`
	ResponseBody         string    `json:"responseBody"`
	IsRetry              bool      `json:"isRetry"`
	DurationMs           int32     `json:"durationMs"`
}

func (q *Queries) LogWebhookAttempt(ctx context.Context, arg LogWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, logWebhookAttempt,
		arg.WebhookDeliveryJobID,
		arg.AttemptNumber,
		arg.HttpStatusCode,
		arg.RequestPayload,
		arg.ResponseBody,
		arg.IsRetry,
		arg.DurationMs,
	)
	return err
}

const resetWebhookJobForRedelivery = `-- name: ResetWebhookJobForRedelivery :one
UPDATE webhook_delivery_jobs
SET status = 'PENDING',
    retry_count = 0,
    next_delivery_at = CURRENT_TIMESTAMP
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at
`

type ResetWebhookJobForRedeliveryParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) ResetWebhookJobForRedelivery(ctx context.Context, arg ResetWebhookJobForRedeliveryParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, resetWebhookJobForRedelivery, arg.ID, arg.ApplicationID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateApplicationWebhook = `-- name: UpdateApplicationWebhook :exec
UPDATE applications
SET webhook_url = $2, webhook_secret = $3, max_retries = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateApplicationWebhookParams struct {
	ID            uuid.UUID `json:"id"`
	WebhookUrl    string    `json:"webhookUrl"`
	WebhookSecret string    `json:"webhookSecret"`
	MaxRetries    int32     `json:"maxRetries"`
}

func (q *Queries) UpdateApplicationWebhook(ctx context.Context, arg UpdateApplicationWebhookParams) error {
	_, err := q.db.Exec(ctx, updateApplicationWebhook,
		arg.ID,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.MaxRetries,
	)
	return err
}

const updateAssignedEmailStatus = `-- name: UpdateAssignedEmailStatus :exec
UPDATE assigned_emails
SET is_active = $2
WHERE id = $1 AND application_id = $3
`

type UpdateAssignedEmailStatusParams struct {
	ID            uuid.UUID `json:"id"`
	IsActive      bool      `json:"isActive"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) UpdateAssignedEmailStatus(ctx context.Context, arg UpdateAssignedEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssignedEmailStatus, arg.ID, arg.IsActive, arg.ApplicationID)
	return err
}

const updateSpooledEmailStatus = `-- name: UpdateSpooledEmailStatus :exec
UPDATE inbound_spool_queue
SET status = $2, attempt_count = attempt_count + 1, last_error_message = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateSpooledEmailStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	Status           SpoolStatus `json:"status"`
	LastErrorMessage string      `json:"lastErrorMessage"`
}

func (q *Queries) UpdateSpooledEmailStatus(ctx context.Context, arg UpdateSpooledEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateSpooledEmailStatus, arg.ID, arg.Status, arg.LastErrorMessage)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1, idp_user_sub = $2, status = $3, created_at = $4, activated_at = $5, last_login_at = $6 WHERE id = $7
`

type UpdateUserParams struct {
	Email       string    `json:"email"`
	IdpUserSub  string    `json:"idpUserSub"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	ActivatedAt time.Time `json:"activatedAt"`
	LastLoginAt time.Time `json:"lastLoginAt"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.IdpUserSub,
		arg.Status,
		arg.CreatedAt,
		arg.ActivatedAt,
		arg.LastLoginAt,
		arg.ID,
	)
	return err
}

const updateWebhookJobStatus = `-- name: UpdateWebhookJobStatus :exec
UPDATE webhook_delivery_jobs  
SET status = $2, retry_count = $3, next_delivery_at = $4  
WHERE id = $1
`

type UpdateWebhookJobStatusParams struct {
	ID             uuid.UUID     `json:"id"`
	Status         WebhookStatus `json:"status"`
	RetryCount     int32         `json:"retryCount"`
	NextDeliveryAt time.Time     `json:"nextDeliveryAt"`
}

func (q *Queries) UpdateWebhookJobStatus(ctx context.Context, arg UpdateWebhookJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookJobStatus,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.NextDeliveryAt,
	)
	return err
}
