// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.public.sql

package public

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkDuplicateWebhookJob = `-- name: CheckDuplicateWebhookJob :one
SELECT EXISTS (
  SELECT 1 FROM webhook_delivery_jobs  
  WHERE application_id = $1 AND ingested_email_id = $2
)
`

type CheckDuplicateWebhookJobParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) CheckDuplicateWebhookJob(ctx context.Context, arg CheckDuplicateWebhookJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDuplicateWebhookJob, arg.ApplicationID, arg.IngestedEmailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createApiKey = `-- name: CreateApiKey :exec
INSERT INTO api_keys (application_id, name, key_prefix, key_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateApiKeyParams struct {
	ApplicationID uuid.UUID `json:"applicationId"`
	Name          string    `json:"name"`
	KeyPrefix     string    `json:"keyPrefix"`
	KeyHash       string    `json:"keyHash"`
	CreatedAt     time.Time `json:"createdAt"`
	ExpiresAt     time.Time `json:"expiresAt"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) error {
	_, err := q.db.Exec(ctx, createApiKey,
		arg.ApplicationID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createAssignedEmail = `-- name: CreateAssignedEmail :one
INSERT INTO assigned_emails (application_id, local_part, description)  
VALUES ($1, $2, $3)  
RETURNING id, application_id, local_part, description, is_active, created_at
`

type CreateAssignedEmailParams struct {
	ApplicationID uuid.UUID   `json:"applicationId"`
	LocalPart     string      `json:"localPart"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateAssignedEmail(ctx context.Context, arg CreateAssignedEmailParams) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, createAssignedEmail, arg.ApplicationID, arg.LocalPart, arg.Description)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createInboundSpooledEmail = `-- name: CreateInboundSpooledEmail :one
INSERT INTO inbound_spool_queue (id, s3_object_key, status, attempt_count, last_error_message, created_at, updated_at)  
VALUES ($1, $2, $3, $4, $5, $6, $7)  
RETURNING id, s3_object_key, status, attempt_count, last_error_message, created_at, updated_at
`

type CreateInboundSpooledEmailParams struct {
	ID               uuid.UUID   `json:"id"`
	S3ObjectKey      string      `json:"s3ObjectKey"`
	Status           SpoolStatus `json:"status"`
	AttemptCount     int32       `json:"attemptCount"`
	LastErrorMessage string      `json:"lastErrorMessage"`
	CreatedAt        time.Time   `json:"createdAt"`
	UpdatedAt        time.Time   `json:"updatedAt"`
}

func (q *Queries) CreateInboundSpooledEmail(ctx context.Context, arg CreateInboundSpooledEmailParams) (InboundSpoolQueue, error) {
	row := q.db.QueryRow(ctx, createInboundSpooledEmail,
		arg.ID,
		arg.S3ObjectKey,
		arg.Status,
		arg.AttemptCount,
		arg.LastErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InboundSpoolQueue
	err := row.Scan(
		&i.ID,
		&i.S3ObjectKey,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIngestedEmail = `-- name: CreateIngestedEmail :one
INSERT INTO ingested_emails (application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix)  
VALUES ($1, $2, $3, $4, $5, $6, $7)  
RETURNING id, application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix, received_at
`

type CreateIngestedEmailParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	AssignedEmailID uuid.UUID `json:"assignedEmailId"`
	ReferenceToken  string    `json:"referenceToken"`
	FromAddress     string    `json:"fromAddress"`
	Subject         string    `json:"subject"`
	MessageID       string    `json:"messageId"`
	S3KeyPrefix     string    `json:"s3KeyPrefix"`
}

func (q *Queries) CreateIngestedEmail(ctx context.Context, arg CreateIngestedEmailParams) (IngestedEmail, error) {
	row := q.db.QueryRow(ctx, createIngestedEmail,
		arg.ApplicationID,
		arg.AssignedEmailID,
		arg.ReferenceToken,
		arg.FromAddress,
		arg.Subject,
		arg.MessageID,
		arg.S3KeyPrefix,
	)
	var i IngestedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.AssignedEmailID,
		&i.ReferenceToken,
		&i.FromAddress,
		&i.Subject,
		&i.MessageID,
		&i.S3KeyPrefix,
		&i.ReceivedAt,
	)
	return i, err
}

const enqueueWebhookJob = `-- name: EnqueueWebhookJob :one
INSERT INTO webhook_delivery_jobs (application_id, ingested_email_id, next_delivery_at)  
VALUES ($1, $2, CURRENT_TIMESTAMP)  
RETURNING id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at
`

type EnqueueWebhookJobParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) EnqueueWebhookJob(ctx context.Context, arg EnqueueWebhookJobParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookJob, arg.ApplicationID, arg.IngestedEmailID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByKeyHash = `-- name: GetApiKeyByKeyHash :one
SELECT id, application_id, name, key_prefix, key_hash, created_at, expires_at, last_user_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetApiKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByKeyHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUserAt,
	)
	return i, err
}

const getApplicationByAPIKey = `-- name: GetApplicationByAPIKey :one
SELECT id, name, api_key_hash, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, created_at, updated_at FROM applications WHERE api_key_hash = $1 LIMIT 1
`

func (q *Queries) GetApplicationByAPIKey(ctx context.Context, apiKeyHash string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByAPIKey, apiKeyHash)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.IsTrusted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, api_key_hash, webhook_url, webhook_secret, aws_iam_role_arn, max_retries, is_trusted, created_at, updated_at FROM applications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.AwsIamRoleArn,
		&i.MaxRetries,
		&i.IsTrusted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationWithEmails = `-- name: GetApplicationWithEmails :many
SELECT a.id, a.name, a.api_key_hash, a.webhook_url, a.webhook_secret, a.aws_iam_role_arn, a.max_retries, a.is_trusted, a.created_at, a.updated_at, e.id AS email_id, e.local_part, e.description, e.is_active, e.created_at AS email_created_at  
FROM applications a  
LEFT JOIN assigned_emails e ON a.id = e.application_id  
WHERE a.id = $1
`

type GetApplicationWithEmailsRow struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	ApiKeyHash     string      `json:"apiKeyHash"`
	WebhookUrl     string      `json:"webhookUrl"`
	WebhookSecret  string      `json:"webhookSecret"`
	AwsIamRoleArn  string      `json:"awsIamRoleArn"`
	MaxRetries     int32       `json:"maxRetries"`
	IsTrusted      bool        `json:"isTrusted"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
	EmailID        pgtype.UUID `json:"emailId"`
	LocalPart      pgtype.Text `json:"localPart"`
	Description    pgtype.Text `json:"description"`
	IsActive       pgtype.Bool `json:"isActive"`
	EmailCreatedAt *time.Time  `json:"emailCreatedAt"`
}

func (q *Queries) GetApplicationWithEmails(ctx context.Context, id uuid.UUID) ([]GetApplicationWithEmailsRow, error) {
	rows, err := q.db.Query(ctx, getApplicationWithEmails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationWithEmailsRow
	for rows.Next() {
		var i GetApplicationWithEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.AwsIamRoleArn,
			&i.MaxRetries,
			&i.IsTrusted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailID,
			&i.LocalPart,
			&i.Description,
			&i.IsActive,
			&i.EmailCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedEmailByLocalPart = `-- name: GetAssignedEmailByLocalPart :one
SELECT id, application_id, local_part, description, is_active, created_at FROM assigned_emails WHERE local_part = $1 AND is_active = TRUE LIMIT 1
`

func (q *Queries) GetAssignedEmailByLocalPart(ctx context.Context, localPart string) (AssignedEmail, error) {
	row := q.db.QueryRow(ctx, getAssignedEmailByLocalPart, localPart)
	var i AssignedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.LocalPart,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getIngestedEmailByID = `-- name: GetIngestedEmailByID :one
SELECT id, application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix, received_at FROM ingested_emails WHERE id = $1 and application_id = $2 LIMIT 1
`

type GetIngestedEmailByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"applicationId"`
}

func (q *Queries) GetIngestedEmailByID(ctx context.Context, arg GetIngestedEmailByIDParams) (IngestedEmail, error) {
	row := q.db.QueryRow(ctx, getIngestedEmailByID, arg.ID, arg.ApplicationID)
	var i IngestedEmail
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.AssignedEmailID,
		&i.ReferenceToken,
		&i.FromAddress,
		&i.Subject,
		&i.MessageID,
		&i.S3KeyPrefix,
		&i.ReceivedAt,
	)
	return i, err
}

const getPendingWebhookJobs = `-- name: GetPendingWebhookJobs :many
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs  
WHERE status = 'PENDING' AND next_delivery_at <= CURRENT_TIMESTAMP  
LIMIT $1
`

func (q *Queries) GetPendingWebhookJobs(ctx context.Context, limit int32) ([]WebhookDeliveryJob, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDeliveryJob
	for rows.Next() {
		var i WebhookDeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.IngestedEmailID,
			&i.Status,
			&i.RetryCount,
			&i.NextDeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, idp_user_sub, status, created_at, activated_at, last_login_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdpUserSub,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, email, idp_user_sub, status, created_at, activated_at, last_login_at FROM users WHERE idp_user_sub = $1
`

func (q *Queries) GetUserBySubject(ctx context.Context, idpUserSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, idpUserSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdpUserSub,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getWebhookJobByIDs = `-- name: GetWebhookJobByIDs :one
SELECT id, application_id, ingested_email_id, status, retry_count, next_delivery_at, created_at FROM webhook_delivery_jobs WHERE application_id = $1 AND ingested_email_id = $2 LIMIT 1
`

type GetWebhookJobByIDsParams struct {
	ApplicationID   uuid.UUID `json:"applicationId"`
	IngestedEmailID uuid.UUID `json:"ingestedEmailId"`
}

func (q *Queries) GetWebhookJobByIDs(ctx context.Context, arg GetWebhookJobByIDsParams) (WebhookDeliveryJob, error) {
	row := q.db.QueryRow(ctx, getWebhookJobByIDs, arg.ApplicationID, arg.IngestedEmailID)
	var i WebhookDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.IngestedEmailID,
		&i.Status,
		&i.RetryCount,
		&i.NextDeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const listIngestedEmailsByApplication = `-- name: ListIngestedEmailsByApplication :many
SELECT id, application_id, assigned_email_id, reference_token, from_address, subject, message_id, s3_key_prefix, received_at FROM ingested_emails WHERE application_id = $1 ORDER BY received_at DESC LIMIT $2 OFFSET $3
`

type ListIngestedEmailsByApplicationParams struct {
	ApplicationID uuid.UUID `json:"applicationId"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListIngestedEmailsByApplication(ctx context.Context, arg ListIngestedEmailsByApplicationParams) ([]IngestedEmail, error) {
	rows, err := q.db.Query(ctx, listIngestedEmailsByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestedEmail
	for rows.Next() {
		var i IngestedEmail
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.AssignedEmailID,
			&i.ReferenceToken,
			&i.FromAddress,
			&i.Subject,
			&i.MessageID,
			&i.S3KeyPrefix,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWebhookAttempt = `-- name: LogWebhookAttempt :exec
INSERT INTO webhook_logs (webhook_delivery_job_id, attempt_number, http_status_code, response_body, is_retry, duration_ms)  
VALUES ($1, $2, $3, $4, $5, $6)
`

type LogWebhookAttemptParams struct {
	WebhookDeliveryJobID uuid.UUID `json:"webhookDeliveryJobId"`
	AttemptNumber        int32     `json:"attemptNumber"`
	HttpStatusCode       int32     `json:"httpStatusCode"`
	ResponseBody         string    `json:"responseBody"`
	IsRetry              bool      `json:"isRetry"`
	DurationMs           int32     `json:"durationMs"`
}

func (q *Queries) LogWebhookAttempt(ctx context.Context, arg LogWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, logWebhookAttempt,
		arg.WebhookDeliveryJobID,
		arg.AttemptNumber,
		arg.HttpStatusCode,
		arg.ResponseBody,
		arg.IsRetry,
		arg.DurationMs,
	)
	return err
}

const updateApplicationWebhook = `-- name: UpdateApplicationWebhook :exec
UPDATE applications
SET webhook_url = $2, webhook_secret = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateApplicationWebhookParams struct {
	ID            uuid.UUID `json:"id"`
	WebhookUrl    string    `json:"webhookUrl"`
	WebhookSecret string    `json:"webhookSecret"`
}

func (q *Queries) UpdateApplicationWebhook(ctx context.Context, arg UpdateApplicationWebhookParams) error {
	_, err := q.db.Exec(ctx, updateApplicationWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecret)
	return err
}

const updateSpooledEmailStatus = `-- name: UpdateSpooledEmailStatus :exec
UPDATE inbound_spool_queue
SET status = $2, attempt_count = attempt_count + 1, last_error_message = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateSpooledEmailStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	Status           SpoolStatus `json:"status"`
	LastErrorMessage string      `json:"lastErrorMessage"`
}

func (q *Queries) UpdateSpooledEmailStatus(ctx context.Context, arg UpdateSpooledEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateSpooledEmailStatus, arg.ID, arg.Status, arg.LastErrorMessage)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1, idp_user_sub = $2, status = $3, created_at = $4, activated_at = $5, last_login_at = $6 WHERE id = $7
`

type UpdateUserParams struct {
	Email       string    `json:"email"`
	IdpUserSub  string    `json:"idpUserSub"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	ActivatedAt time.Time `json:"activatedAt"`
	LastLoginAt time.Time `json:"lastLoginAt"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.IdpUserSub,
		arg.Status,
		arg.CreatedAt,
		arg.ActivatedAt,
		arg.LastLoginAt,
		arg.ID,
	)
	return err
}

const updateWebhookJobStatus = `-- name: UpdateWebhookJobStatus :exec
UPDATE webhook_delivery_jobs  
SET status = $2, retry_count = $3, next_delivery_at = $4  
WHERE id = $1
`

type UpdateWebhookJobStatusParams struct {
	ID             uuid.UUID     `json:"id"`
	Status         WebhookStatus `json:"status"`
	RetryCount     int32         `json:"retryCount"`
	NextDeliveryAt time.Time     `json:"nextDeliveryAt"`
}

func (q *Queries) UpdateWebhookJobStatus(ctx context.Context, arg UpdateWebhookJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookJobStatus,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.NextDeliveryAt,
	)
	return err
}
