FROM node:24.12.0-alpine AS builder
WORKDIR /build

RUN corepack enable

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/dashboard/package.json ./apps/dashboard/

COPY apps/dashboard/ ./apps/dashboard/

RUN ls -altr ./apps/dashboard

# Note: The --prod flag is omitted here to install devDependencies needed for the build
RUN pnpm install --filter dashboard

RUN pnpm --filter dashboard build

FROM nginx:stable-alpine

COPY --from=builder /build/apps/dashboard/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

